const array = [];
const array1 = ['Влад', 'Андрей', 'Наталья'];
const array2 = ['Яблоко', 'Апельсин', 'Мандарин'];
const b = array2[0];
console.log(b);
const c = array2[2];
console.log(c);
const f = array2[3];
console.log(f);
const length = array2.length;
console.log(length);
array2[0] = 'Мандарин';
console.log(array2[0]);
array2.push('Яблоко');
console.log(array2[3]);
array2.pop();
console.log(array2[3]);
array2.splice(1, 1);
console.log(array2[1]);
console.log(array2.length);
array2.splice(-1, 1, 'Яблоко', 'Яблоко');
console.log(array2[1]);
console.log(array2[2]);
const newArray = array2.slice(1, 3);
console.log(newArray);
